import { describe, expect, it, vi } from "vitest";
import type { ActionAdapter } from "../src/modules/automation/action-registry.js";
import type { AutomationExecution, PlannedAction } from "../src/modules/automation/automation.model.js";
import { AutomationWorker, type AutomationWorkerRepository } from "../src/modules/automation/automation.worker.js";

const action = (id: string, maxAttempts = 2, baseDelayMs = 100): PlannedAction => ({ id, type: "task.update", config: {}, retry: { maxAttempts, baseDelayMs }, sensitive: false, compensationType: "task.update" });
const execution = (actions = [action("a"), action("b")]): AutomationExecution => ({ _id: "exec", eventId: "event", ruleId: "rule", ruleVersionId: "v1", status: "running", event: { eventId: "event", type: "task.updated", source: "audit", occurredAt: "2026-01-01T00:00:00.000Z", scope: {}, payload: {} }, plan: { actions, requiresApproval: false, inputFingerprint: "fp" }, attempts: [], createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" });

class Repo implements AutomationWorkerRepository {
  constructor(public item?: AutomationExecution) {}
  async claimExecution(owner: string, now: Date, until: Date) { if (!this.item || !["running", "compensating"].includes(this.item.status) || (this.item.nextAttemptAt && new Date(this.item.nextAttemptAt) > now) || (this.item.lease && this.item.lease.until > now)) return undefined; this.item.lease = { owner, until }; return structuredClone(this.item); }
  async renewLease(id: string, owner: string, until: Date) { if (!this.item || this.item._id !== id || this.item.lease?.owner !== owner) return false; this.item.lease.until = until; return true; }
  async saveExecution(value: AutomationExecution, owner: string) { if (!this.item || this.item.lease?.owner !== owner) return false; this.item = structuredClone(value); return true; }
  async releaseLease(id: string, owner: string, now: Date) { if (!this.item || this.item._id !== id || this.item.lease?.owner !== owner) return false; this.item.lease.until = now; return true; }
}
function harness(item = execution(), adapters: Record<string, Partial<ActionAdapter>> = {}) {
  let time = new Date("2026-01-01T00:00:00.000Z"); const repo = new Repo(item); const calls: string[] = [];
  const lookup = (type: string) => ({ type, sensitive: false, validate() {}, preview: async () => ({}), execute: async (_c: unknown, x: { idempotencyKey: string }) => { calls.push(x.idempotencyKey); return { id: calls.length }; }, compensate: async (_c: unknown, _r: unknown, x: { idempotencyKey: string }) => { calls.push(x.idempotencyKey); return {}; }, ...adapters[type] }) as ActionAdapter;
  const worker = new AutomationWorker(repo, lookup, { owner: "worker", now: () => time, setTimer: vi.fn(() => 1), clearTimer: vi.fn(), alert: vi.fn() });
  return { worker, repo, calls, advance(ms: number) { time = new Date(time.getTime() + ms); } };
}

describe("AutomationWorker", () => {
  it("executes actions in order with stable keys and succeeds", async () => { const h = harness(); await h.worker.tick(); expect(h.calls).toEqual(["exec:a:execute", "exec:b:execute"]); expect(h.repo.item?.status).toBe("succeeded"); });
  it("compensates succeeded actions in reverse after a terminal failure", async () => { const h = harness(execution([action("a"), action("b"), action("c", 1)]), { "task.update": { execute: async (c, x) => { h.calls.push(x.idempotencyKey); if (x.idempotencyKey.endsWith(":c:execute")) throw Object.assign(new Error("bad"), { transient: false }); return { action: x.idempotencyKey }; }, compensate: async (_c, _r, x) => { h.calls.push(x.idempotencyKey); return {}; } } }); await h.worker.tick(); expect(h.calls).toEqual(["exec:a:execute", "exec:b:execute", "exec:c:execute"]); expect(h.repo.item?.status).toBe("compensating"); await h.worker.tick(); expect(h.calls.slice(3)).toEqual(["exec:b:compensate", "exec:a:compensate"]); expect(h.repo.item?.status).toBe("rolled_back"); });
  it("durably backs off transient errors and does not retry early", async () => { let n = 0; const h = harness(execution([action("a", 2, 100)]), { "task.update": { execute: async () => { n++; if (n === 1) throw Object.assign(new Error("later"), { transient: true }); return {}; } } }); await h.worker.tick(); expect(h.repo.item?.nextAttemptAt).toBe("2026-01-01T00:00:00.100Z"); await h.worker.tick(); expect(n).toBe(1); h.advance(100); await h.worker.tick(); expect(n).toBe(2); expect(h.repo.item?.status).toBe("succeeded"); });
  it("does not retry permanent errors", async () => { let n = 0; const h = harness(execution([action("a", 3)]), { "task.update": { execute: async () => { n++; throw Object.assign(new Error("denied"), { code: "permission" }); } } }); await h.worker.tick(); expect(n).toBe(1); expect(h.repo.item?.status).toBe("compensating"); });
  it("alerts when compensation exhausts retries", async () => { const item = execution([action("a", 1)]); item.status = "compensating"; item.attempts.push({ actionId: "a", operation: "execute", attempt: 1, status: "succeeded", startedAt: item.createdAt, completedAt: item.createdAt, result: {} }); const h = harness(item, { "task.update": { compensate: async () => { throw Object.assign(new Error("broken"), { transient: false }); } } }); await h.worker.tick(); expect(h.repo.item?.status).toBe("compensation_failed"); expect(vi.mocked((h.worker as unknown as { alert: ReturnType<typeof vi.fn> }).alert)).toHaveBeenCalled(); });
  it("resumes without repeating succeeded execution and supports expired lease takeover", async () => { const item = execution(); item.attempts.push({ actionId: "a", operation: "execute", attempt: 1, status: "succeeded", startedAt: item.createdAt, completedAt: item.createdAt, result: {} }); item.lease = { owner: "dead", until: new Date("2025-12-31T23:59:59Z") }; const h = harness(item); await h.worker.tick(); expect(h.calls).toEqual(["exec:b:execute"]); });
  it("retries compensation after durable backoff", async () => { const item = execution([action("a", 2, 100)]); item.status = "compensating"; item.attempts.push({ actionId: "a", operation: "execute", attempt: 1, status: "succeeded", startedAt: item.createdAt, completedAt: item.createdAt, result: {} }); let n = 0; const h = harness(item, { "task.update": { compensate: async () => { n++; if (n === 1) throw Object.assign(new Error("later"), { transient: true }); return {}; } } }); await h.worker.tick(); expect(h.repo.item?.nextAttemptAt).toBe("2026-01-01T00:00:00.100Z"); await h.worker.tick(); expect(n).toBe(1); h.advance(100); await h.worker.tick(); expect(n).toBe(2); expect(h.repo.item?.status).toBe("rolled_back"); });
  it("releases its lease and will not take over an unexpired foreign lease", async () => { const item = execution([action("a")]); item.lease = { owner: "other", until: new Date("2026-01-01T00:01:00Z") }; const h = harness(item); await h.worker.tick(); expect(h.calls).toEqual([]); h.advance(60_000); await h.worker.tick(); expect(h.calls).toEqual(["exec:a:execute"]); expect(h.repo.item?.lease?.until).toEqual(new Date("2026-01-01T00:01:00Z")); });
  it("durably fails an unregistered action without rejecting the tick", async () => { const repo = new Repo(execution([action("a", 1)])); const worker = new AutomationWorker(repo, () => { throw new Error("Unsupported automation action: task.update"); }, { owner: "worker", now: () => new Date("2026-01-01T00:00:00Z") }); await expect(worker.tick()).resolves.toBeUndefined(); expect(repo.item?.attempts.at(-1)).toMatchObject({ actionId: "a", status: "failed", error: "Unsupported automation action: task.update" }); expect(repo.item?.status).toBe("compensating"); });
  it("reports a tick error and schedules the next poll", async () => { const callbacks: Array<() => void> = []; const onError = vi.fn(); const repo = { claimExecution: vi.fn().mockRejectedValue(new Error("db down")), renewLease: vi.fn(), saveExecution: vi.fn(), releaseLease: vi.fn() } as unknown as AutomationWorkerRepository; const worker = new AutomationWorker(repo, () => { throw new Error("unused"); }, { setTimer: vi.fn((callback: () => void) => { callbacks.push(callback); return callbacks.length as never; }), clearTimer: vi.fn(), onError }); worker.start(); callbacks[0](); await vi.waitFor(() => expect(callbacks).toHaveLength(2)); expect(onError).toHaveBeenCalledWith(expect.objectContaining({ message: "db down" })); await worker.stop(); });
  it("persists terminal compensation failure when alert rejects", async () => { const item = execution([action("a", 1)]); item.status = "compensating"; item.attempts.push({ actionId: "a", operation: "execute", attempt: 1, status: "succeeded", startedAt: item.createdAt, result: {} }); const repo = new Repo(item); const alert = vi.fn().mockRejectedValue(new Error("alert down")); const adapter = { type: "task.update", sensitive: false, validate() {}, preview: async () => ({}), execute: async () => ({}), compensate: async () => { throw new Error("broken"); } } as ActionAdapter; const worker = new AutomationWorker(repo, () => adapter, { owner: "worker", now: () => new Date("2026-01-01T00:00:00Z"), alert }); await expect(worker.tick()).resolves.toBeUndefined(); expect(repo.item?.status).toBe("compensation_failed"); expect(repo.item?.attempts.at(-1)?.status).toBe("compensation_failed"); });
  it("does not let a hanging alert block tick or stop", async () => { const item = execution([action("a", 1)]); item.status = "compensating"; item.attempts.push({ actionId: "a", operation: "execute", attempt: 1, status: "succeeded", startedAt: item.createdAt, result: {} }); const repo = new Repo(item); const adapter = { type: "task.update", sensitive: false, validate() {}, preview: async () => ({}), execute: async () => ({}), compensate: async () => { throw new Error("broken"); } } as ActionAdapter; const worker = new AutomationWorker(repo, () => adapter, { owner: "worker", now: () => new Date("2026-01-01T00:00:00Z"), alert: () => new Promise(() => undefined), alertTimeoutMs: 1, sleep: async () => undefined }); await worker.tick(); await expect(worker.stop()).resolves.toBeUndefined(); expect(repo.item?.status).toBe("compensation_failed"); });
  it("does not overlap ticks and stop waits for the active tick", async () => { let release!: () => void, entered!: () => void; const pending = new Promise<void>(r => { release = r; }); const adapterEntered = new Promise<void>(r => { entered = r; }); let calls = 0; const h = harness(execution([action("a")]), { "task.update": { execute: async () => { calls++; entered(); await pending; return {}; } } }); const first = h.worker.tick(); await adapterEntered; await h.worker.tick(); expect(calls).toBe(1); const stopped = h.worker.stop(); release(); await first; await stopped; });
  it("starts one bounded polling timer and clears it on stop", async () => { const h = harness(); h.worker.start(); h.worker.start(); expect((h.worker as unknown as { setTimer: ReturnType<typeof vi.fn> }).setTimer).toHaveBeenCalledTimes(1); await h.worker.stop(); expect((h.worker as unknown as { clearTimer: ReturnType<typeof vi.fn> }).clearTimer).toHaveBeenCalledTimes(1); });
});
