import { useEffect, useState, type ReactNode } from "react";
import { useQueryClient } from "@tanstack/react-query";
type RealtimeEvent = { _id: string; type: string; entityId: string; projectId?: string; occurredAt: string; version: number; payload?: Record<string, unknown> };
type ConnectionState = "connecting" | "online" | "offline" | "polling";
const eventTypes = ["task.created", "task.updated", "task.deleted", "task.status_changed", "task.comment_added", "task.checklist_updated", "project.updated", "project.member_updated", "user.updated", "notification.failed", "operations.updated"];
export function RealtimeProvider({ children }: { children: ReactNode }) { const queryClient = useQueryClient(); const [state, setState] = useState<ConnectionState>("connecting"); useEffect(() => { let source: EventSource | undefined; let retry: ReturnType<typeof setTimeout> | undefined; let stopped = false; let lastEventId = sessionStorage.getItem("realtime:last-event-id") || ""; const connect = () => { if (stopped) return; setState("connecting"); const suffix = lastEventId ? `?lastEventId=${encodeURIComponent(lastEventId)}` : ""; source = new EventSource(`/api/realtime/events${suffix}`, { withCredentials: true }); source.addEventListener("connected", () => setState("online")); const handle = (message: MessageEvent<string>) => { const event = JSON.parse(message.data) as RealtimeEvent; if (message.lastEventId) { lastEventId = message.lastEventId; sessionStorage.setItem("realtime:last-event-id", lastEventId); } if (event.type.startsWith("task.")) { void queryClient.invalidateQueries({ queryKey: ["tasks"] }); void queryClient.invalidateQueries({ queryKey: ["dashboard"] }); } else if (event.type.startsWith("project.")) { void queryClient.invalidateQueries({ queryKey: ["projects"] }); void queryClient.invalidateQueries({ queryKey: ["tasks"] }); } else if (event.type.startsWith("user.")) void queryClient.invalidateQueries({ queryKey: ["users"] }); else void queryClient.invalidateQueries({ queryKey: ["operations"] }); window.dispatchEvent(new CustomEvent("app:realtime", { detail: event })); }; for (const type of eventTypes) source.addEventListener(type, handle as EventListener); source.onerror = () => { setState("offline"); source?.close(); retry = setTimeout(connect, 3000); }; };
    fetch("/api/realtime/config", { credentials: "same-origin" }).then((response) => response.ok ? response.json() as Promise<{ enabled: boolean }> : Promise.resolve({ enabled: false })).then((config) => { if (stopped) return; if (config.enabled) connect(); else setState("polling"); }).catch(() => setState("polling"));
    return () => { stopped = true; if (retry) clearTimeout(retry); source?.close(); };
  }, [queryClient]); const label = state === "online" ? "Trực tuyến" : state === "connecting" ? "Đang kết nối" : state === "polling" ? "Polling dự phòng" : "Đang kết nối lại"; return <><div className={`realtime-status ${state}`} title="Kết nối cập nhật thời gian thực"><span />{label}</div>{children}</>; }
