import { EventEmitter } from "events";
import { randomUUID } from "crypto";
import { createClient, type RedisClientType } from "redis";
import { env } from "../../config/env.js";
import { database } from "../../core/database.js";
import { logger } from "../../core/logger.js";
export type RealtimeEventType = "task.created" | "task.updated" | "task.deleted" | "task.status_changed" | "task.comment_added" | "task.checklist_updated" | "project.updated" | "project.member_updated" | "user.updated" | "notification.failed" | "operations.updated";
export interface RealtimeEvent { _id: string; type: RealtimeEventType; entityId: string; projectId?: string; userId?: string; actor?: string; occurredAt: string; version: number; payload?: Record<string, unknown>; expiresAt: Date; }
const channel = `project-management:${env.nodeEnv}:events`; const emitter = new EventEmitter(); emitter.setMaxListeners(10000);
const options = env.redisHost ? { socket: { host: env.redisHost, port: env.redisPort }, password: env.redisPassword || undefined } : undefined;
let publisher: RedisClientType | undefined; let subscriber: RedisClientType | undefined; let publishedEvents = 0; let receivedEvents = 0; let publishFailures = 0; let activeConnections = 0;
export async function startRealtime() { if (!env.realtimeEnabled || !options) return; try { publisher = createClient(options); subscriber = publisher.duplicate(); publisher.on("error", (error) => logger.error("realtime_redis_publisher_error", { error })); subscriber.on("error", (error) => logger.error("realtime_redis_subscriber_error", { error })); await Promise.all([publisher.connect(), subscriber.connect()]); await subscriber.subscribe(channel, (message) => { try { receivedEvents += 1; emitter.emit("event", JSON.parse(message) as RealtimeEvent); } catch (error) { logger.warn("realtime_event_parse_failed", { error }); } }); logger.info("realtime_redis_connected", { channel }); } catch (error) { logger.warn("realtime_redis_unavailable_using_local_bus", { error }); publisher = undefined; subscriber = undefined; } }
export async function stopRealtime() { await Promise.all([subscriber?.isOpen ? subscriber.close() : Promise.resolve(), publisher?.isOpen ? publisher.close() : Promise.resolve()]); }
export async function publishRealtimeEvent(input: Omit<RealtimeEvent, "_id" | "occurredAt" | "version" | "expiresAt">) { if (!env.realtimeEnabled) return; const now = new Date(); const event: RealtimeEvent = { _id: randomUUID(), ...input, occurredAt: now.toISOString(), version: Date.now(), expiresAt: new Date(now.getTime() + 24 * 3600000) }; await (await database()).collection<RealtimeEvent>("realtime_events").insertOne(event); publishedEvents += 1; if (publisher?.isReady) { try { await publisher.publish(channel, JSON.stringify(event)); } catch (error) { publishFailures += 1; logger.warn("realtime_redis_publish_failed_using_local_bus", { error }); emitter.emit("event", event); } } else emitter.emit("event", event); logger.debug("realtime_event_published", { eventId: event._id, type: event.type, entityId: event.entityId, projectId: event.projectId }); return event; }
export function subscribeRealtime(listener: (event: RealtimeEvent) => void) { emitter.on("event", listener); return () => emitter.off("event", listener); }
export async function replayEvents(lastEventId: string, limit = 100) { const col = (await database()).collection<RealtimeEvent>("realtime_events"); const previous = await col.findOne({ _id: lastEventId }); if (!previous) return []; return col.find({ occurredAt: { $gt: previous.occurredAt } }).sort({ occurredAt: 1 }).limit(limit).toArray(); }

export function changeRealtimeConnections(delta: number) { activeConnections = Math.max(0, activeConnections + delta); }
export function getRealtimeStats() { return { enabled: env.realtimeEnabled, redisConnected: Boolean(publisher?.isReady && subscriber?.isReady), activeConnections, publishedEvents, receivedEvents, publishFailures }; }
