import { useState } from "react";
import { AnimatedContent, CountUp, ShinyText, SpotlightCard, StarBorder } from "../../components/react-bits/ReactBits";
import { ReviewGridLogo } from "../../components/brand/ReviewGridLogo";
import "./landing.css";

const capabilities = [
  ["01", "PR becomes accountable work", "GitHub Pull Request events create or update tasks with project, sprint, owner, priority and deadline."],
  ["02", "Review with complete context", "Keep diff, checklist, discussion and delivery metadata together instead of reconstructing context across tools."],
  ["03", "Move at webhook speed", "Realtime updates, optimistic UI and resilient polling keep every reviewer aligned without refreshing the board."],
  ["04", "Operate with evidence", "Audit trails, retry queues and dead-letter visibility give administrators a defensible operating record."]
];
const faq = [
  ["Does it replace GitHub?", "No. ReviewGrid turns GitHub delivery signals into accountable review work while GitHub remains the source of code truth."],
  ["What happens when a webhook fails?", "Deliveries use exponential retry. Terminal failures move to a visible dead-letter queue where an administrator can inspect and replay them."],
  ["Can developers edit project metadata?", "Role-based permissions separate status updates from administrative fields. Every sensitive action is validated server-side."],
  ["Does realtime require Redis?", "Not for a single instance. Redis Pub/Sub coordinates multiple instances; polling remains as a 60-second fallback."]
];

function ProductPreview() { return <div className="pf-preview"><aside><ReviewGridLogo compact /><span>▦</span><span>◇</span><span>⌁</span></aside><div><header><p><small>Review operations</small><strong>Good morning, Linh</strong></p><i>● Live</i></header><div className="pf-metrics">{[["Open reviews","24"],["Needs changes","7"],["Ready to merge","11"],["Overdue","2"]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong><small>Across 6 projects</small></article>)}</div><div className="pf-board"><article><b>IN REVIEW · #482</b><h3>Harden webhook signature validation</h3><p>Platform API · Sprint 18</p><span className="pf-urgent">High priority</span></article><article><b>READY · #476</b><h3>Add optimistic task status updates</h3><p>Client App · Sprint 18</p><span>3/3 checks complete</span></article><article className="pf-ai-card"><b>OPERATIONS BRIEF</b><h3>Two reviews need intervention today.</h3><p>One deadline risk and one delivery in retry.</p><button>Review signals →</button></article></div></div></div>; }

export function LandingPage({ onLogin }: { onLogin: () => void }) {
  const [openFaq, setOpenFaq] = useState(0);
  return <div className="pf-landing">
    <nav className="pf-nav"><a href="#landing-hero" className="pf-logo"><ReviewGridLogo showTagline /></a><div><a href="#landing-workflow">Workflow</a><a href="#landing-capabilities">Product</a><a href="#landing-security">Security</a><a href="#landing-pricing">Pricing</a></div><button onClick={onLogin}>Sign in</button></nav>
    <section id="landing-hero" className="pf-hero"><AnimatedContent><label>GitHub Pull Request intelligence, operationalized</label><h1>Every review.<br/><ShinyText>Clearly owned.</ShinyText></h1><p>ReviewGrid converts pull requests into accountable delivery work—complete with context, deadlines, realtime status and an operational audit trail.</p><div className="pf-actions"><StarBorder as="button" onClick={onLogin} className="pf-primary">Start reviewing <span>→</span></StarBorder><a href="#landing-workflow">See the workflow</a></div><small>Deploy on your infrastructure · GitHub App ready · Role-based access</small></AnimatedContent><AnimatedContent delay={.15}><ProductPreview/></AnimatedContent></section>
    <section className="pf-trust"><p>Designed for engineering teams where review quality affects delivery</p><div><span>GITHUB APP</span><span>REALTIME SSE</span><span>MONGODB</span><span>REDIS PUB/SUB</span><span>AUDIT LOG</span></div></section>
    <section id="landing-workflow" className="pf-section"><header><span>One connected review loop</span><h2>From webhook to decision—without losing context.</h2></header><div className="pf-steps">{[["01","Receive","Verify GitHub signatures and repository policy."],["02","Structure","Create a task with owner, sprint and deadline."],["03","Review","Track diff context, checklist and discussion."],["04","Operate","Notify, audit, retry and report in realtime."]].map(([n,t,c],i)=><AnimatedContent delay={i*.08} key={n}><article><b>{n}</b><i>↘</i><h3>{t}</h3><p>{c}</p></article></AnimatedContent>)}</div></section>
    <section id="landing-capabilities" className="pf-section pf-capabilities"><header><span>Built for review operations</span><h2>Engineering signal becomes accountable work.</h2></header><div>{capabilities.map(([n,t,c])=><SpotlightCard key={n} className="pf-cap-card"><b>{n}</b><h3>{t}</h3><p>{c}</p><a href="#landing-final-cta">Explore capability →</a></SpotlightCard>)}</div></section>
    <section className="pf-proof"><blockquote>“We stopped discovering blocked reviews in stand-up. ReviewGrid tells us who owns the next move before delivery drifts.”</blockquote><p><strong>Engineering Operations</strong><small>Multi-project product team</small></p><div>{[[42,"%","faster review handoff"],[99.9,"%","traceable delivery events"],[8,"x","automatic retry attempts"]].map(([n,s,l])=><article key={String(l)}><strong><CountUp to={Number(n)} suffix={String(s)}/></strong><span>{l}</span></article>)}</div></section>
    <section id="landing-security" className="pf-section pf-security"><header><span>Operational trust</span><h2>Secure at every boundary. Observable at every failure.</h2></header><div>{[["HMAC","Verified webhook signatures and repository allowlists."],["RBAC","Superadmin, admin, manager and developer permissions."],["AUDIT","Request IDs and structured action trails."],["RESILIENCE","Retry queue, dead-letter recovery and health probes."]].map(([t,c])=><article key={t}><b>{t}</b><p>{c}</p></article>)}</div></section>
    <section id="landing-pricing" className="pf-section pf-pricing"><header><span>Deployment</span><h2>Own the workflow. Own the data.</h2></header><div><article><b>SELF-HOSTED</b><h3>Production foundation</h3><p>For teams ready to operate ReviewGrid inside their own environment.</p><strong>Open deployment</strong><ul><li>✓ Docker-first setup</li><li>✓ GitHub App integration</li><li>✓ MongoDB and optional Redis</li><li>✓ Full operations dashboard</li></ul><button onClick={onLogin}>Open workspace →</button></article><aside><span>Included by design</span><h3>No artificial feature gates.</h3><p>The platform is built as operational infrastructure: security, auditability, realtime updates and failure recovery are part of the foundation—not premium add-ons.</p></aside></div></section>
    <section id="landing-faq" className="pf-section pf-faq"><header><span>Due diligence</span><h2>Questions engineering leaders ask.</h2></header><div>{faq.map(([q,a],i)=><article className={openFaq===i?"open":""} key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{q}</span><b>⌄</b></button><p>{a}</p></article>)}</div></section>
    <section id="landing-final-cta" className="pf-final"><span>THE NEXT PULL REQUEST</span><h2>Review with context.<br/><ShinyText>Deliver with confidence.</ShinyText></h2><p>Turn your GitHub review stream into a clear operating system for engineering delivery.</p><StarBorder as="button" onClick={onLogin} className="pf-primary">Start reviewing <span>→</span></StarBorder></section>
    <footer><a href="#landing-hero" className="pf-logo"><ReviewGridLogo /></a><p>PR review operations for teams that take delivery personally.</p><small>© 2026 ReviewGrid</small></footer>
  </div>;
}
