import { AnimatedContent, CountUp, ShinyText, SpotlightCard, StarBorder } from "../../components/react-bits/ReactBits";
import { ReviewGridLogo } from "../../components/brand/ReviewGridLogo";

export function VietnameseLandingPage({ onLogin }: { onLogin: () => void }) {
  return <div className="pf-landing pf-vi">
    <section id="landing-hero" className="pf-hero"><AnimatedContent><label>Biến tín hiệu GitHub thành vận hành có trách nhiệm</label><h1>Mọi lượt review.<br/><ShinyText>Đều có người sở hữu.</ShinyText></h1><p>ReviewGrid chuyển Pull Request thành công việc rõ ràng với đầy đủ ngữ cảnh, người phụ trách, thời hạn, trạng thái realtime và lịch sử vận hành có thể kiểm chứng.</p><div className="pf-actions"><StarBorder as="button" onClick={onLogin} className="pf-primary">Bắt đầu review <span>→</span></StarBorder><a href="#landing-workflow">Xem quy trình</a></div><small>Tự triển khai · Sẵn sàng cho GitHub App · Phân quyền theo vai trò</small></AnimatedContent><AnimatedContent delay={.15}><div className="pf-preview"><aside><ReviewGridLogo compact /><span>▦</span><span>◇</span><span>⌁</span></aside><div><header><p><small>Vận hành review</small><strong>Chào buổi sáng, Linh</strong></p><i>● Trực tuyến</i></header><div className="pf-metrics">{[["Đang review","24"],["Cần sửa","7"],["Sẵn sàng merge","11"],["Quá hạn","2"]].map(([l,v])=><article key={l}><span>{l}</span><strong>{v}</strong><small>Trên 6 dự án</small></article>)}</div><div className="pf-board"><article><b>ĐANG REVIEW · #482</b><h3>Tăng cường xác thực chữ ký webhook</h3><p>Platform API · Sprint 18</p><span>Ưu tiên cao</span></article><article><b>SẴN SÀNG · #476</b><h3>Cập nhật trạng thái task tối ưu</h3><p>Client App · Sprint 18</p><span>Hoàn thành 3/3 kiểm tra</span></article><article className="pf-ai-card"><b>TÓM TẮT VẬN HÀNH</b><h3>Hai lượt review cần xử lý hôm nay.</h3><p>Một nguy cơ trễ hạn và một webhook đang retry.</p></article></div></div></div></AnimatedContent></section>
    <section className="pf-trust"><p>Dành cho đội kỹ thuật coi chất lượng review là một phần của năng lực giao hàng</p><div><span>GITHUB APP</span><span>REALTIME SSE</span><span>MONGODB</span><span>REDIS PUB/SUB</span><span>AUDIT LOG</span></div></section>
    <section id="landing-workflow" className="pf-section"><header><span>Một vòng review kết nối</span><h2>Từ webhook đến quyết định—không đánh mất ngữ cảnh.</h2></header><div className="pf-steps">{[["01","Tiếp nhận","Xác thực chữ ký GitHub và chính sách repository."],["02","Cấu trúc","Tạo task với người phụ trách, sprint và thời hạn."],["03","Review","Theo dõi diff, checklist và thảo luận tại một nơi."],["04","Vận hành","Thông báo, audit, retry và cập nhật realtime."]].map(([n,t,c],i)=><AnimatedContent delay={i*.08} key={n}><article><b>{n}</b><i>↘</i><h3>{t}</h3><p>{c}</p></article></AnimatedContent>)}</div></section>
    <section id="landing-capabilities" className="pf-section pf-capabilities"><header><span>Được xây cho vận hành review</span><h2>Tín hiệu kỹ thuật trở thành công việc có trách nhiệm.</h2></header><div>{[["01","PR thành công việc rõ ràng","Webhook tạo task với dự án, sprint, người phụ trách và deadline."],["02","Review đủ ngữ cảnh","Diff, checklist, trao đổi và metadata giao hàng ở cùng một nơi."],["03","Đồng bộ theo thời gian thực","Optimistic UI, SSE và polling dự phòng giữ mọi reviewer đồng bộ."],["04","Vận hành có bằng chứng","Audit, retry queue và dead-letter giúp mọi thất bại đều quan sát được."]].map(([n,t,c])=><SpotlightCard key={n} className="pf-cap-card"><b>{n}</b><h3>{t}</h3><p>{c}</p><a href="#landing-final-cta">Khám phá →</a></SpotlightCard>)}</div></section>
    <section className="pf-proof"><blockquote>“Chúng tôi không còn phát hiện review bị nghẽn trong daily stand-up. ReviewGrid cho biết ai cần hành động trước khi tiến độ trôi đi.”</blockquote><p><strong>Engineering Operations</strong><small>Đội sản phẩm đa dự án</small></p><div>{[[42,"%","bàn giao review nhanh hơn"],[99.9,"%","event có thể truy vết"],[8,"x","số lần retry tự động"]].map(([n,s,l])=><article key={String(l)}><strong><CountUp to={Number(n)} suffix={String(s)}/></strong><span>{l}</span></article>)}</div></section>
    <section id="landing-security" className="pf-section pf-security"><header><span>Niềm tin vận hành</span><h2>An toàn tại mọi ranh giới. Quan sát được mọi thất bại.</h2></header><div>{[["HMAC","Xác thực chữ ký webhook và repository được phép."],["RBAC","Phân quyền superadmin, admin, manager và developer."],["AUDIT","Request ID và lịch sử hành động có cấu trúc."],["RESILIENCE","Retry queue, dead-letter và health probe."]].map(([t,c])=><article key={t}><b>{t}</b><p>{c}</p></article>)}</div></section>
    <section id="landing-pricing" className="pf-section pf-pricing"><header><span>Triển khai</span><h2>Làm chủ quy trình. Làm chủ dữ liệu.</h2></header><div><article><b>SELF-HOSTED</b><h3>Nền tảng production</h3><p>Cho đội ngũ muốn vận hành ReviewGrid trong hạ tầng riêng.</p><strong>Triển khai mở</strong><ul><li>✓ Thiết lập bằng Docker</li><li>✓ Tích hợp GitHub App</li><li>✓ MongoDB và Redis tùy chọn</li><li>✓ Dashboard vận hành đầy đủ</li></ul><button onClick={onLogin}>Mở workspace →</button></article><aside><span>Có sẵn từ nền tảng</span><h3>Không chia nhỏ tính năng thiết yếu.</h3><p>Bảo mật, audit, realtime và phục hồi lỗi là nền móng của hệ thống, không phải tiện ích trả thêm.</p></aside></div></section>
    <section id="landing-faq" className="pf-section pf-faq"><header><span>Thẩm định kỹ thuật</span><h2>Câu hỏi từ những người vận hành cẩn trọng.</h2></header><div>{[["Có thay thế GitHub không?","Không. GitHub vẫn là nguồn sự thật của code; ReviewGrid tổ chức trách nhiệm và vận hành review."],["Webhook lỗi thì sao?","Hệ thống retry theo exponential backoff và đưa lỗi cuối vào dead-letter queue để kiểm tra, chạy lại."],["Developer có sửa metadata không?","Không. Phân quyền tách cập nhật trạng thái khỏi trường quản trị và được kiểm tra phía server."],["Realtime có bắt buộc Redis không?","Không với một instance. Redis điều phối nhiều instance; polling 60 giây luôn là phương án dự phòng."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <section id="landing-final-cta" className="pf-final"><span>PULL REQUEST TIẾP THEO</span><h2>Review đủ ngữ cảnh.<br/><ShinyText>Giao hàng đầy tự tin.</ShinyText></h2><p>Biến luồng review GitHub thành hệ điều hành rõ ràng cho năng lực giao hàng kỹ thuật.</p><StarBorder as="button" onClick={onLogin} className="pf-primary">Bắt đầu review <span>→</span></StarBorder></section>
    <footer><a href="#landing-hero" className="pf-logo"><ReviewGridLogo /></a><p>Vận hành PR review cho đội ngũ nghiêm túc với chất lượng giao hàng.</p><small>© 2026 ReviewGrid</small></footer>
  </div>;
}
