import { useEffect, useState } from "react";
import { api } from "../../api/client";
export type ProjectRole = "owner" | "manager" | "member" | "viewer";
export type Project = { _id: string; name: string; description: string; team?: string; members: { email: string; role: ProjectRole }[] };
export function Projects() {
  const [projects, setProjects] = useState<Project[]>([]); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [team, setTeam] = useState(""); const [memberEmail, setMemberEmail] = useState<Record<string, string>>({}); const [memberRole, setMemberRole] = useState<Record<string, ProjectRole>>({}); const [message, setMessage] = useState("");
  const load = () => api<Project[]>("/projects").then(setProjects); useEffect(() => { void load(); }, []);
  return <main><h2>Projects</h2><p>{message}</p><form onSubmit={async (e) => { e.preventDefault(); try { await api("/projects", { method: "POST", body: JSON.stringify({ name, description, team }) }); setName(""); setDescription(""); setTeam(""); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Create failed"); } }}><input required maxLength={120} placeholder="Project name" value={name} onChange={(e) => setName(e.target.value)} /><textarea maxLength={5000} placeholder="Description" value={description} onChange={(e) => setDescription(e.target.value)} /><input maxLength={100} placeholder="Team" value={team} onChange={(e) => setTeam(e.target.value)} /><button>Create project</button></form>{projects.map((project) => <article key={project._id}><h3>{project.name}</h3><p>{project.description}</p><p>Team: {project.team || "—"}</p><ul>{project.members.map((member) => <li key={member.email}>{member.email} · {member.role}</li>)}</ul><form onSubmit={async (e) => { e.preventDefault(); const email = memberEmail[project._id]; if (!email) return; try { await api(`/projects/${project._id}/members/${encodeURIComponent(email)}`, { method: "PUT", body: JSON.stringify({ role: memberRole[project._id] || "member" }) }); setMemberEmail({ ...memberEmail, [project._id]: "" }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Member update failed"); } }}><input required type="email" placeholder="Member email" value={memberEmail[project._id] || ""} onChange={(e) => setMemberEmail({ ...memberEmail, [project._id]: e.target.value })} /><select value={memberRole[project._id] || "member"} onChange={(e) => setMemberRole({ ...memberRole, [project._id]: e.target.value as ProjectRole })}>{["owner", "manager", "member", "viewer"].map((role) => <option key={role}>{role}</option>)}</select><button>Add/update member</button></form></article>)}</main>;
}
