import { useEffect, useState } from "react";
import { api } from "../../api/client";
type User = { id: string; email: string; role: string; active: boolean; createdAt: string };
export function Users() {
  const [users, setUsers] = useState<User[]>([]); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState("developer"); const [message, setMessage] = useState("");
  const load = () => api<User[]>("/auth/users").then(setUsers); useEffect(() => { void load(); }, []);
  async function update(id: string, body: Record<string, unknown>) { try { await api(`/auth/users/${id}`, { method: "PATCH", body: JSON.stringify(body) }); setMessage("User updated. Existing sessions were revoked."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Update failed"); } }
  return <main><h2>Users</h2><p>{message}</p><form onSubmit={async (e) => { e.preventDefault(); await api("/auth/users", { method: "POST", body: JSON.stringify({ email, password, role }) }); setEmail(""); setPassword(""); void load(); }}><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" /><input required minLength={12} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" /><select value={role} onChange={(e) => setRole(e.target.value)}>{["admin", "manager", "developer"].map((item) => <option key={item}>{item}</option>)}</select><button>Create user</button></form><ul>{users.map((user) => <li key={user.id}>{user.email} · <select disabled={user.role === "superadmin"} value={user.role} onChange={(e) => void update(user.id, { role: e.target.value })}>{["superadmin", "admin", "manager", "developer"].map((item) => <option key={item}>{item}</option>)}</select> · {user.active ? "active" : "disabled"} <button disabled={user.role === "superadmin"} onClick={() => void update(user.id, { active: !user.active })}>{user.active ? "Disable" : "Enable"}</button> <button onClick={() => { const next = prompt("New password (minimum 12 characters)"); if (next) void update(user.id, { password: next }); }}>Reset password</button></li>)}</ul></main>;
}
