import { randomUUID } from "node:crypto";
import type { ActionAdapter } from "./action-registry.js";
import type { ActionAttempt, ActionType, AutomationExecution, PlannedAction } from "./automation.model.js";
export interface AutomationWorkerRepository { claimExecution(owner: string, now: Date, until: Date): Promise<AutomationExecution | undefined>; renewLease(id: string, owner: string, until: Date): Promise<boolean>; saveExecution(execution: AutomationExecution, owner: string): Promise<boolean>; releaseLease(id: string, owner: string, now: Date): Promise<boolean>; }
type Timer = ReturnType<typeof setTimeout>;
type Dependencies = { owner?: string; now?: () => Date; pollMs?: number; setTimer?: (callback: () => void, ms: number) => Timer; clearTimer?: (timer: Timer) => void; alert?: (event: Record<string, unknown>) => Promise<void> | void; alertTimeoutMs?: number; sleep?: (ms: number) => Promise<void>; onError?: (error: unknown) => void };
export class AutomationWorker {
  private readonly owner: string; private readonly now: () => Date; private readonly pollMs: number; private readonly alertTimeoutMs: number; private readonly sleep: (ms: number) => Promise<void>; private readonly onError: (error: unknown) => void; private timer?: Timer; private active?: Promise<void>; private stopped = true;
  readonly setTimer: (callback: () => void, ms: number) => Timer; readonly clearTimer: (timer: Timer) => void; readonly alert: NonNullable<Dependencies["alert"]>;
  constructor(private readonly repository: AutomationWorkerRepository, private readonly lookup: (type: ActionType) => ActionAdapter, dependencies: Dependencies = {}) { this.owner = dependencies.owner ?? randomUUID(); this.now = dependencies.now ?? (() => new Date()); this.pollMs = dependencies.pollMs ?? 1000; this.setTimer = dependencies.setTimer ?? ((callback, ms) => setTimeout(callback, ms)); this.clearTimer = dependencies.clearTimer ?? clearTimeout; this.alert = dependencies.alert ?? (() => undefined); this.alertTimeoutMs = dependencies.alertTimeoutMs ?? 1000; this.sleep = dependencies.sleep ?? (ms => new Promise(resolve => setTimeout(resolve, ms))); this.onError = dependencies.onError ?? (() => undefined); }
  start() { if (!this.stopped) return; this.stopped = false; const poll = async () => { if (this.stopped) return; try { await this.tick(); } catch (error) { this.report(error); } finally { if (!this.stopped) this.timer = this.setTimer(() => void poll(), this.pollMs); } }; this.timer = this.setTimer(() => void poll(), 0); }
  async stop() { this.stopped = true; if (this.timer !== undefined) { this.clearTimer(this.timer); this.timer = undefined; } await this.active; }
  async tick() { if (this.active) return; const work = this.run(); this.active = work; try { await work; } finally { if (this.active === work) this.active = undefined; } }
  private report(error: unknown) { try { this.onError(error); } catch { /* reporting must never stop polling */ } }
  private async notify(event: Record<string, unknown>) { const notification = Promise.resolve().then(() => this.alert(event)).catch(error => this.report(error)); await Promise.race([notification, this.sleep(this.alertTimeoutMs)]); }
  private async run() { const now = this.now(); const e = await this.repository.claimExecution(this.owner, now, new Date(now.getTime() + 60_000)); if (!e) return; let primary: unknown; try { if (e.status === "running") await this.execute(e); else await this.compensate(e); } catch (error) { primary = error; throw error; } finally { try { await this.repository.releaseLease(e._id, this.owner, this.now()); } catch (releaseError) { if (primary === undefined) throw releaseError; this.report(releaseError); } } }
  private async persist(e: AutomationExecution) { e.updatedAt = this.now().toISOString(); if (!await this.repository.saveExecution(e, this.owner)) throw new Error("Automation execution lease lost"); }
  private async renew(e: AutomationExecution) { if (!await this.repository.renewLease(e._id, this.owner, new Date(this.now().getTime() + 60_000))) throw new Error("Automation execution lease lost"); }
  private attempts(e: AutomationExecution, id: string, op: "execute" | "compensate") { return e.attempts.filter(x => x.actionId === id && (x.operation ?? "execute") === op).length; }
  private succeeded(e: AutomationExecution, id: string) { return [...e.attempts].reverse().find(x => x.actionId === id && (x.operation ?? "execute") === "execute" && x.status === "succeeded"); }
  private compensated(e: AutomationExecution, id: string) { return e.attempts.some(x => x.actionId === id && x.operation === "compensate" && x.status === "compensated"); }
  private transient(error: unknown) { return typeof error === "object" && error !== null && "transient" in error && (error as { transient?: boolean }).transient === true; }
  private delay(a: PlannedAction, n: number) { return a.retry.baseDelayMs * 2 ** (n - 1); }
  private async execute(e: AutomationExecution) { delete e.nextAttemptAt; for (const a of e.plan.actions) { if (this.succeeded(e, a.id)) continue; const n = this.attempts(e, a.id, "execute") + 1, attempt: ActionAttempt = { actionId: a.id, operation: "execute", attempt: n, status: "running", startedAt: this.now().toISOString() }; e.attempts.push(attempt); await this.persist(e); await this.renew(e); try { const adapter = this.lookup(a.type); attempt.result = await adapter.execute(a.config, { event: e.event, executionId: e._id, idempotencyKey: `${e._id}:${a.id}:execute` }); attempt.status = "succeeded"; attempt.completedAt = this.now().toISOString(); await this.persist(e); } catch (error) { attempt.status = "failed"; attempt.error = error instanceof Error ? error.message : String(error); attempt.completedAt = this.now().toISOString(); if (this.transient(error) && n < a.retry.maxAttempts) e.nextAttemptAt = new Date(this.now().getTime() + this.delay(a, n)).toISOString(); else e.status = "compensating"; await this.persist(e); return; } } e.status = "succeeded"; delete e.nextAttemptAt; await this.persist(e); }
  private async compensate(e: AutomationExecution) { delete e.nextAttemptAt; for (const a of [...e.plan.actions].reverse()) { const prior = this.succeeded(e, a.id); if (!prior || this.compensated(e, a.id)) continue; const n = this.attempts(e, a.id, "compensate") + 1, attempt: ActionAttempt = { actionId: a.id, operation: "compensate", attempt: n, status: "running", startedAt: this.now().toISOString() }; e.attempts.push(attempt); await this.persist(e); await this.renew(e); try { await this.lookup(a.type).compensate(a.config, prior.result ?? {}, { event: e.event, executionId: e._id, idempotencyKey: `${e._id}:${a.id}:compensate` }); attempt.status = "compensated"; attempt.completedAt = this.now().toISOString(); await this.persist(e); } catch (error) { attempt.status = "compensation_failed"; attempt.error = error instanceof Error ? error.message : String(error); attempt.completedAt = this.now().toISOString(); if (this.transient(error) && n < a.retry.maxAttempts) e.nextAttemptAt = new Date(this.now().getTime() + this.delay(a, n)).toISOString(); else e.status = "compensation_failed"; await this.persist(e); if (e.status === "compensation_failed") await this.notify({ priority: "high", type: "automation.compensation_failed", executionId: e._id, actionId: a.id, error: attempt.error }); return; } } e.status = "rolled_back"; delete e.nextAttemptAt; await this.persist(e); }
}
